/* 商圈店家互動程式。原始157筆資料保持不動；第二層分類只在顯示層合併。 */
(() => {
  const data=Array.isArray(window.MERCHANTS)?window.MERCHANTS:[],list=document.getElementById('list'),hint=document.getElementById('hint'),mapbox=document.getElementById('mapbox'),search=document.getElementById('search'),subfilters=document.getElementById('subfilters');let group='全部',sub='全部';
  const SUB_RULES={'美食餐飲':[['鍋物燒烤',/牛排\/鍋物|火鍋|鍋物|燒肉|串燒|居酒屋|熱炒|海鮮|牛排/],['早餐輕食',/早餐|咖啡\/輕食/],['甜點飲品',/冰品|點心|飲料|咖啡|麵食\/飲料/],['正餐小吃',/日式|韓式|義式|俄式|港式|台日西式|台式|餐廳|餐飲|複合餐飲|鐵板料理|自助餐|快餐|丼飯|日式豬排|咖哩|小吃|麵食|鍋燒|鍋貼|水餃|熟食|便當|海鮮鍋燒/]],'購物零售':[['民生購物',/便利商店|超市|量販|生活百貨|文具|雜貨|零售/],['3C通訊',/3C通訊/],['服飾配件',/服飾|服飾配件|帽類|珠寶/]],'居家服務':[['居家修繕',/裝潢五金|五金|建材|窗簾|家具/],['房屋服務',/房仲/]],'醫療保健':[['診所醫療',/親子診所|耳鼻喉科|兒科|過敏|內科|牙醫/],['藥局中藥',/藥局|中藥行/]],'生活服務':[['汽機車',/汽車美容|洗車|鍍膜|機車維修|汽車|機車/],['寵物',/動物醫院|寵物店\/美容|寵物美容|寵物店|寵物用品|水族/],['美容美髮',/美髮|理髮|美容|養生/],['日常服務',/洗衣|修鞋|停車場|停車|物流取件|公司辦公室/]],'教育休閒':[['教育學習',/補習班/],['休閒遊樂',/公園|娃娃機|遊樂/]]};
  const FALLBACK={'美食餐飲':'正餐小吃','購物零售':'民生購物','居家服務':'居家修繕','醫療保健':'診所醫療','生活服務':'日常服務','教育休閒':'休閒遊樂'};
  const displayGroup=x=>x.group==='醫療保健'&&/動物醫院/.test(x.sub||'')?'生活服務':x.group;
  function displaySub(x){const g=displayGroup(x),hit=(SUB_RULES[g]||[]).find(([,p])=>p.test(x.sub||''));return hit?hit[0]:(FALLBACK[g]||'其他');}
  const mapHtml=q=>'<iframe id="map" title="商圈店家地圖" loading="eager" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q='+encodeURIComponent(q)+'&output=embed"></iframe>';
  function resetMap(){document.querySelectorAll('.card').forEach(c=>c.classList.remove('sel'));hint.textContent='商圈店家地圖｜點選商家查看位置';mapbox.innerHTML=mapHtml('藍田高大特區 高雄 楠梓');}
  function renderSubs(){if(group==='全部'){subfilters.innerHTML='';sub='全部';return;}const configured=(SUB_RULES[group]||[]).map(([l])=>l),actual=[...new Set(data.filter(x=>displayGroup(x)===group).map(displaySub))],subs=configured.filter(x=>actual.includes(x));subfilters.innerHTML='<button type="button" data-sub="全部" class="active">全部</button>'+subs.map(x=>'<button type="button" data-sub="'+x+'">'+x+'</button>').join('');subfilters.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{sub=btn.dataset.sub;subfilters.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===btn));resetMap();render();}));}
  function filtered(){const q=(search?.value||'').trim().toLowerCase();return data.filter(x=>(group==='全部'||displayGroup(x)===group)&&(sub==='全部'||displaySub(x)===sub)&&(!q||`${x.name} ${x.address} ${x.sub} ${displaySub(x)} ${x.area}`.toLowerCase().includes(q)));}
  function selectMerchant(id){const x=data.find(v=>String(v.id)===String(id));if(!x)return;document.querySelectorAll('.card').forEach(c=>c.classList.toggle('sel',String(c.dataset.id)===String(id)));hint.textContent=x.name+'｜'+x.address;mapbox.innerHTML=mapHtml((x.address||x.name)+' 高雄市楠梓區');}
  function render(){const rows=filtered();list.innerHTML=rows.map(x=>`<article class="card" role="button" tabindex="0" data-id="${x.id}"><div class="name">${x.name}</div><div><span class="tag">${displaySub(x)}</span></div><div class="meta">${x.address||''}</div></article>`).join('')||'<div class="card">目前沒有符合的店家</div>';}
  list.addEventListener('click',e=>{const c=e.target.closest('.card[data-id]');if(c){e.preventDefault();selectMerchant(c.dataset.id);}});
  list.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const c=e.target.closest('.card[data-id]');if(c){e.preventDefault();selectMerchant(c.dataset.id);}}});
  document.querySelectorAll('button[data-g]').forEach(btn=>btn.addEventListener('click',()=>{group=btn.dataset.g;sub='全部';if(search)search.value='';document.querySelectorAll('button[data-g]').forEach(b=>b.classList.toggle('active',b===btn));renderSubs();resetMap();render();window.scrollTo({top:0,behavior:'smooth'});}));
  if(search)search.addEventListener('input',()=>{resetMap();render();});
  document.querySelector('button[data-g="全部"]')?.classList.add('active');renderSubs();resetMap();render();
})();